name: 'wt.tools-load-secrets'
description: 'Fetches JSON from an HTTP endpoint and sets the keys as environment variables'
inputs:
  presigned_url:
    description: 'Presigned URL that includes authentication and path to secrets'
    required: false
  apikey: 
    description: 'wt.tools API key (not required if using presigned_url)'
    required: false
  apisecret:
    description: 'wt.tools API secret (not required if using presigned_url)'
    required: false
  project:
    description: 'Project identifier (not required if using presigned_url)'
    required: false
  environment:
    description: 'Environment name (not required if using presigned_url)'
    required: false
  env_prefix:
    description: 'Prefix for environment variables to prevent clashes'
    required: false
    default: ''
  outputs_prefix:
    description: 'Prefix to add to output keys to prevent clashes'
    required: false
    default: ''
  upper_case_env_keys:
    description: 'uppercase environment variable keys (including prefix)'
    required: false
    default: false
  api_base_url:
    description: 'Override the default API base URL (not required if using presigned_url)'
    required: false
    default: 'https://api.wt.tools'
    
runs:
  using: 'node16'
  main: 'dist/index.js'